# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "http://mwalterskirchen.dev"

[_.globalMeta]
title = "Maximilian Walterskirchen"
description = "Senior Full Stack Engineer based in ZurichðŸ‡¨ðŸ‡­"
longDescription = "Senior Full Stack Engineer based in ZurichðŸ‡¨ðŸ‡­. Passionate about AI, Web Development and Cybersecurity."
cardImage = "/avatar.jpeg"
keywords = ["web development", "design", "technology"]

[_.blogMeta]
title = "Blog"
description = "Practical wisdom, unfiltered thoughts, and hot takes."
longDescription = "AI, Web Development, Cybersecurity and the occasional programming mishap."
cardImage = "/avatar.jpeg"
keywords = ["web development", "design", "technology"]

[_.projectMeta]
title = "Projects"
description = "A list of my web development projects and developer tools."
longDescription = "All of my projects, including both frontend and full-stack applications."
cardImage = "/avatar.jpeg"
keywords = ["web development", "design", "technology"]

[_.notFoundMeta]
title = "Not Found - 404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "/avatar.jpeg"

[_.hero]
title = "Maximilian Walterskirchen"
subtitle = "Senior Full Stack Engineer based in ZurichðŸ‡¨ðŸ‡­"
image = "/avatar.jpeg"

[_.personal]
name = "Maximilian Walterskirchen"
githubProfile = "https://github.com/mwalterskirchen"
linkedinProfile = "https://linkedin.com/in/mwalterskirchen"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.about]
description = """
Senior Full Stack Engineer with <span class='-zag-bg text-nowrap -zag-text zag-transition px-2 py-1 text-sm font-semibold'>5+ years</span> experience building scalable web applications. </br> </br>
I've helped international clients from FinTech startups to enterprises transform ideas into robust solutions. <br /><br />
Passionate about ðŸ§  AI integration, ðŸ”’ cybersecurity, and modern web technologies. Always ready to tackle complex challenges and build something amazing. <br /><br />
Let's create the future together. ðŸš€
"""
title = "About Me"
skillsTitle = "Technologies"
skills = [
    "TypeScript",
    "React",
    "Node.js",
    "LLM / Generative AI",
    "Docker",
    "CI/CD",
    "Cybersecurity",
    "AWS",
    "Azure",
    "GCP",
    "Terraform",
    "Git",
    "Python",
    "Java",
    "Databases",
]

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"
